### ISSUE TITLE
Build fails with Vulkan SDK 1.4.350: vk_enum_string_helper.h mismatches bundled Vulkan-Headers (v335)

### ISSUE THREAD

**Issue by tentax143** [KytyPS5/KytyPS5#25]
## Summary

  The README lists "Vulkan SDK 1.3 or newer" as a build requirement, but building
  with the current SDK (1.4.350.0) fails. The repo bundles Vulkan-Headers at
  header version 335 (`3rdparty/Vulkan-Headers`), which is first in the include
  path — but `vk_enum_string_helper.h` is not part of Vulkan-Headers (it ships
  with the SDK, from Vulkan-Utility-Libraries). So the ~14 sources that include
  it get the SDK 1.4.350 copy, which references enums that don't exist in the
  v335 `vulkan_core.h`.

  ## Error

  First failure is in `src/graphics/host_gpu/renderer/renderCompute.cpp`:

      C:\VulkanSDK\1.4.350.0\Include\vulkan/vk_enum_string_helper.h(1291,14):
      error: use of undeclared identifier
      'VK_STRUCTURE_TYPE_DEVICE_FAULT_SHADER_ABORT_MESSAGE_INFO_KHR'

  followed by similar undeclared-identifier errors until the error limit.

  ## Steps to reproduce

  1. Install Vulkan SDK 1.4.350.0 (current latest)
  2. Configure and build per the README (clang-cl + Ninja, Windows)
  3. Compilation fails in every file that includes `<vulkan/vk_enum_string_helper.h>`

  ## Workaround

  Install Vulkan SDK **1.4.335.0**, which matches the bundled headers exactly —
  the build then succeeds.

  ## Suggested fixes

  Any of these would prevent the trap:
  - Document the supported/pinned SDK version in the README instead of "1.3 or newer"
  - Add a CMake configure-time check comparing the SDK's `VK_HEADER_VERSION`
    against the bundled Vulkan-Headers version, failing with a clear message
  - Vendor a matching `vk_enum_string_helper.h` so the SDK copy is never used

  I'm happy to submit a PR for whichever direction the maintainers prefer.

  ## Environment

  - Windows 11, VS 2022 Build Tools with clang-cl 19.1.5
  - CMake 4.4.0, Ninja 1.13.2, Qt 6.8.3
  - Repo at current `main` (f743a48), submodules at pinned revisions

  ## AI disclosure

  Per the project's AI-use policy: I used an AI tool (Claude Code) to help
  diagnose the header mismatch and identify the affected include chain. I
  personally reproduced the failure (clean build with Vulkan SDK 1.4.350.0),
  confirmed the exact error output above, and verified that installing SDK
  1.4.335.0 resolves it by completing a full build and running the emulator.
  This issue text was reviewed and edited by me.
